"""
FastAPI application and route definitions — the JUSTIS Hub-style integration point.

Real-world grounding
--------------------
The CCSF JUSTIS 5-Year Roadmap (Gartner, 2019) describes a "JUSTIS Hub" as
the central integration middleware connecting all 8 participating agencies.
The Hub is responsible for routing requests between agency systems, enforcing
access policies, and exposing normalized data to authorized consumers.

This API service plays that hub role in the demo: it is the single entry point
through which all identity normalization and access decisions flow, regardless
of which agency's identity is presenting or which agency's data is being
requested. A real hub would additionally handle message routing, event
streaming, and SLA monitoring across the agency network.

All business logic lives in access_engine.py and anomaly.py. This module is
responsible only for:
  - wiring HTTP routes to those functions
  - translating ValueError / missing-data conditions to appropriate HTTP errors
  - CORS configuration for local development

API surface
-----------
GET  /api/health                    liveness check
GET  /api/agencies                  list all agencies (with LASO contacts)
GET  /api/identities                list all mock identities
GET  /api/identities/{identity_id}  fetch a single identity (with raw payload)
GET  /api/case/{case_id}            fetch a case record (unfiltered)
POST /api/access-decision           evaluate access for an identity + case
POST /api/anomaly/simulate          run the anomaly detector against a simulated session

Interactive docs (auto-generated by FastAPI) are available at /docs when the
server is running locally.
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from .models import AccessDecisionRequest, AccessDecisionResponse, AnomalyAlert, AnomalyRequest
from .data import AGENCIES, IDENTITIES, CASE_RECORD
from .person_data import PERSON_RECORDS, MATCH_CANDIDATES
from .source_registry import REGISTRY
from .access_engine import evaluate_case_access
from .anomaly import evaluate_anomaly

app = FastAPI(title="Federated Identity ABAC Demo API")

# CORS is permissive for local development only. In a Netlify deployment the
# frontend and API share the same origin, so this middleware is not needed.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/api/health")
def health():
    """Liveness check. Returns immediately with no dependencies."""
    return {"status": "ok"}


@app.get("/api/agencies")
def list_agencies():
    """Return all participating agencies, including their LASO security contacts."""
    return list(AGENCIES.values())


@app.get("/api/identities")
def list_identities():
    """
    Return all mock identities, including each identity's raw protocol payload.
    The raw payload is used by the UI to show the before/after normalization view.
    """
    return list(IDENTITIES.values())


@app.get("/api/identities/{identity_id}")
def get_identity(identity_id: str):
    """Fetch a single identity by its internal ID."""
    identity = IDENTITIES.get(identity_id)
    if not identity:
        raise HTTPException(status_code=404, detail=f"Identity '{identity_id}' not found")
    return identity


@app.get("/api/case/{case_id}")
def get_case(case_id: str):
    """
    Return the full, unfiltered case record.

    This endpoint is used by the UI to render the "unfiltered baseline" view
    before any identity is selected, so the user can see what access control
    removes. It does not apply any access decisions.
    """
    if case_id != CASE_RECORD.case_id:
        raise HTTPException(status_code=404, detail=f"Case '{case_id}' not found")
    return CASE_RECORD


@app.post("/api/access-decision", response_model=AccessDecisionResponse)
def access_decision(request: AccessDecisionRequest):
    """
    Evaluate the given identity's access to every field in the given case.

    Returns one FieldAccessResult per field, each containing the decision
    (visible / hidden / redacted), the filtered value, and a plain-English
    reason explaining why that decision was made.

    This is the core endpoint the UI calls whenever the user switches identity.
    """
    identity = IDENTITIES.get(request.identity_id)
    if not identity:
        raise HTTPException(status_code=404, detail=f"Identity '{request.identity_id}' not found")
    if request.case_id != CASE_RECORD.case_id:
        raise HTTPException(status_code=404, detail=f"Case '{request.case_id}' not found")
    return evaluate_case_access(identity, CASE_RECORD)


@app.post("/api/anomaly/simulate", response_model=AnomalyAlert)
def simulate_anomaly(request: AnomalyRequest):
    """
    Run the anomaly detector against a simulated access session.

    The caller provides the identity, a simulated access count, and an
    off-hours flag. The detector applies its rule set and returns an alert
    payload — including the LASO routing target — whether or not the alert
    triggered, so the UI can show both outcomes.
    """
    try:
        return evaluate_anomaly(request)
    except ValueError as e:
        # evaluate_anomaly raises ValueError for unknown identity IDs.
        raise HTTPException(status_code=404, detail=str(e))


# ── Person identity resolution routes ────────────────────────────────────────


@app.get("/api/persons")
def list_persons():
    """Return all canonical person records, each with their linked source records."""
    return list(PERSON_RECORDS.values())


@app.get("/api/persons/{person_id}")
def get_person(person_id: str):
    """Fetch a single canonical person record by ID."""
    person = PERSON_RECORDS.get(person_id)
    if not person:
        raise HTTPException(status_code=404, detail=f"Person '{person_id}' not found")
    return person


@app.get("/api/matches/pending")
def get_pending_matches():
    """Return all match candidates currently in pending status."""
    return [m for m in MATCH_CANDIDATES.values() if m.status == "pending"]


@app.post("/api/matches/{match_id}/approve")
def approve_match(match_id: str):
    """
    Mark a match candidate as approved, linking the source record to the
    canonical person. The updated match is returned so the UI can update
    its state without a separate fetch.
    """
    match = MATCH_CANDIDATES.get(match_id)
    if not match:
        raise HTTPException(status_code=404, detail=f"Match '{match_id}' not found")
    MATCH_CANDIDATES[match_id] = match.model_copy(update={"status": "approved"})
    return MATCH_CANDIDATES[match_id]


@app.post("/api/matches/{match_id}/reject")
def reject_match(match_id: str):
    """Mark a match candidate as rejected. The source record remains unlinked."""
    match = MATCH_CANDIDATES.get(match_id)
    if not match:
        raise HTTPException(status_code=404, detail=f"Match '{match_id}' not found")
    MATCH_CANDIDATES[match_id] = match.model_copy(update={"status": "rejected"})
    return MATCH_CANDIDATES[match_id]


# ── Source system field registry ─────────────────────────────────────────────


@app.get("/api/source-systems")
def list_source_systems():
    """
    Return all source system configurations from the field registry.

    Each entry declares which PII fields a source system can contribute to
    person identity matching and the classification of each field
    (unique_identifier, quasi_identifier, or descriptor).
    """
    return list(REGISTRY.values())
